- node错误监控

同步方法中的错误:

try{}catch(){}

异步回调捕获err

```js

process.on('uncaughtException', (err) => {
  console.error('uncaught', err)
})
 
process.on('unhandledRejection', (reason, p) => {
  console.error('unhandle', reason, p)

```